[folder_watcher]
folder_path = "/watch"
sleep_time = 60
ffnet_disable = false

[smtp]
server = ""
port = 587
username = ""
password = ""
from_email = ""

[calibre]
path=""
username=""
password=""
default_ini="/config/defaults.ini"
personal_ini="/config/personal.ini"
update_method="update"

[pushbullet]
enabled = false
api_key = ""
device = ""

[apprise]
# List of Apprise URLs to send notifications to.
# For example:
# urls = [
#   "pbul://PUSHBULLET_API_KEY",  # For Pushbullet
#   "discord://WEBHOOK_ID/WEBHOOK_TOKEN", # For Discord
#   "mailto://USER:PASSWORD@HOST:PORT", # For Email
# ]
urls = []